### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by aouone** [ErrorErrorError/msi-gs65-gs75-hackintosh#2]
As the Dgpu won't work for HDMi and miniDP, is there methods to use usb c to connect monitor. For example,  to fix Thunderport 3. I failed to connect my monitor with a usbc to DP cable as there is no thunderport 3 device.

**Comment by erikbdev** [comment]
@aouone upload your clover files. My thunderbolt 3 is able to output to an external monitor.

**Comment by aouone** [comment]
Hello, https://github.com/aouone/GS65/tree/master/EFI/CLOVER this is my clover folder and it works actually pretty well. Sorry for that I didn't actually try your clover files before my issuing, because mine works pretty well. My clover just lack the support of Thunderport 3. Could you help me on that? I tested your one on my machine. It's pretty much perfect but do you have the issue that the mouse cursor can hardly move just the moment when you see the login page ? It happens when it just boot and wake up from sleep.

**Comment by erikbdev** [comment]
> It's pretty much perfect but do you have the issue that the mouse cursor can hardly move just the moment when you see the login page ? It happens when it just boot and wake up from sleep.

I actually don't have this issue since I am using VoodooI2C, which provides native gesture support. The only thing is that with the latest build it causes Kernel Panic. 

EDIT: I think I solved that issue by adding NoTouchID.kext but I forgot to commit it on GitHub. The reason why it causes the computer to hardly move the mouse on startup is because it's trying to find the TouchID to unlock the computer.


> Hello, https://github.com/aouone/GS65/tree/master/EFI/CLOVER this is my clover folder

I will check it out in a bit.

EDIT: Have you tried removing SSDT-Thunderbolt.aml and connecting from Thunderbolt to HDMI?

EDIT2: Try changing your SMBios to MacbookPro15,2. I had an issue where I couldn't use my hdmi or miniDP from my MSI GE62 6QD and It was because the SMBios. Maybe that's the reason why your Thunderbolt is not working properly.

**Comment by erikbdev** [comment]
Closing due to no inactivity.
